spring:
  application:
    name: hr-payroll
    cloud:
      loadbalancer:
        clients:
          hr-worker:
            instances:
              - uri: http://localhost:8081
              - uri: http://localhost:8082
server:
  port: 8101


